plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ebr.drillviewer'
    compileSdk 34

    defaultConfig {
        applicationId 'com.ebr.drillviewer'
        minSdk 21
        targetSdk 34
        versionCode 113
        versionName '1.1.3'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
